- name: Identifica el primer disco libre #Codigo del profesor en el foro
  set_fact:
    disks: "/dev/{{ item.key }}"
  when:
        # si el disco no está particionado tendrá libre 
        # estas variables de los facts
     - not item.value.partitions
     - not item.value.holders
     - not item.value.links.uuids
     - not item.value.links.labels
        # los discos serán /dev/vd? o /dev/sd? filtramos el
        # resto de resultados
     - item.key | regex_search ("vd|sd")
  with_dict: "{{ ansible_devices }}"

- name: Muestra el disco vacío
  debug: msg="Disco vacio {{ disks }}"
  when: disks is defined


- name: Crea el volumen físico
  shell: pvcreate "{{ disks }}"

- name: Crea vgp
  lvg:
      vg: data_vg 
      pvs: "{{ disks }}"

- name: Crea un volumen lógico del tamaño de todo el espacio restante en el grupo de volúmenes
  lvol:
    vg: data_vg
    lv: nfs_lv
    size: 100%FREE

- name:  Crear el filesystem de tipo XFS
  filesystem:
    fstype: xfs
    dev: /dev/data_vg/nfs_lv 

- name: Crea un directorio si no existe
  file:
    path: /srv/nfs
    state: directory


- name: Monta la unidad
  mount:
    src: /dev/data_vg/nfs_lv
    path: /srv/nfs 
    fstype: xfs
    state: mounted

