apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-volumes
  namespace: webapp-volumes
  labels:
    app: webapp-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-volumes
  template:
    metadata:
      labels:
        app: webapp-volumes
    spec:
      containers:
      - name: webapp-volumes
        image: quay.io/rhte_2019/webapp:v1
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        volumeMounts:
        - name: site-pvc
          mountPath: /var/www/public
      volumes:
      - name: site-pvc
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: volumes-service
    namespace: webapp-volumes
spec:
    selector:
      app: webapp-volumes
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
