- name: identifica el primer disco libre #Codigo del profesor en el foro
  set_fact:
    disks: "/dev/{{ item.key }}"
  when:
        # si el disco no está particionado tendrá libre 
        # estas variables de los facts
     - not item.value.partitions
     - not item.value.holders
     - not item.value.links.uuids
     - not item.value.links.labels
        # los discos serán /dev/vd? o /dev/sd? filtramos el
        # resto de resultados
     - item.key | regex_search ("vd|sd")
  with_dict: "{{ ansible_devices }}"

- name: mostrar
  debug: msg="Disco vacio {{ disks }}"
  when: disks is defined


- name: Physical volume creation
  shell: pvcreate "{{ disks }}"

- name: create vgp
  lvg:
      vg: data_vg 
      pvs: "{{ disks }}"

- name: Create a logical volume the size of all remaining space in the volume group
  lvol:
    vg: data_vg
    lv: nfs_lv
    size: 100%FREE

- name:  crear el filesystem de tipo XFS
  filesystem:
    fstype: xfs
    dev: /dev/data_vg/nfs_lv 

- name: Create a directory if it does not exist
  file:
    path: /srv/nfs
    state: directory


- name: Mount drive
  mount:
    src: /dev/data_vg/nfs_lv
    path: /srv/nfs 
    fstype: xfs
    state: mounted

#- name: Enable and start nfs-server
#  systemd:
#   name: chronyd
#   state: started
#   enabled: yes

#- name: Add a line to a file if the file does not exist, without passing regexp
#  lineinfile:
#    path: /etc/exports
#    line: "/srv/nfs {{item}}(rw,sync)"
#    create: yes
#  with_items:
#    - 10.0.1.10
#    - 10.0.1.11
#    - 10.0.1.12

#- name: reload service exportfs
#  shell: exportfs -r

#- name: reload service exportfs
#  shell: exportfs -s
