- name: Configuramos kudeadm
  shell: |
          kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Download file from a file path
  get_url:
    url: https://docs.projectcalico.org/manifests/custom-resources.yaml
    dest: /tmp/custom-resources.yaml


- name: hange CDR.
  replace:
     path: /tmp/custom-resources.yaml
     replace: "cidr: 192.169.0.0/16 #"
     regexp: 'cidr:'
- name: Configuramos kudeadm
  shell: |
          kubectl apply -f /tmp/custom-resources.yaml

