- name: Actualizaci칩n de im치genes
  shell: |
          kubeadm config images pull

- name: Inicializaci칩n de Kubernetes
  shell: |
          kubeadm init --pod-network-cidr "{{networkcidr}}"

- name: Obtenci칩n del token
  shell: |
          kubeadm token create --print-join-command
  register: kube_token

- name: Guardamos el comando join.
  set_fact:
         kube_token: "{{kube_token.stdout_lines[0]}}"

- name: Configuramos kudeadm
  shell: |
         export KUBECONFIG=/etc/kubernetes/admin.conf

- name: Configuramos kudeadm
  shell: |
         mkdir -p /root/.kube

- name: Configuramos kudeadm
  shell: |
         cp -i /etc/kubernetes/admin.conf /root/.kube/config

- name: Configuramos kudeadm
  shell: |
         chown $(id -u):$(id -g) /root/.kube/config
