- name: Get token
  shell: |
          kubeadm token create --print-join-command
  register: kube_token
- name: Applying token to fact.
  set_fact:
         kube_token: "{{kube_token.stdout_lines[0]}}"

