- name: initial setup
  hosts: [master,worker]
  vars_files:
    - "group_vars/config_vars.yaml"
  become: true
  gather_facts: true
  roles:
   - system_update       
#   - time_sync
   - set_up_nodes
